# Docker version 24.0.2 (compose v2)

# @note debugging: could use profiles with prebuild images

# restart always ensures restart on error (health checks for example)

services:
  nginx: # lightweight webserver
    profiles: ["default", "server"]
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    restart: always

  mariadb: # database server
    profiles: ["default", "db"]
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data:
    driver: local

