# Docker version 25.0.3 (windows)
# Docker version 26.0.2, build 3c863ff

name: inception

services:
  mariadb:  #database service
    profiles: ["default", "db"]
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

# wordpress: #php & wordpress service
#   profiles: ["default", "wp"]
#   build:
#     context: ./requirements/wordpress
#     dockerfile: Dockerfile
#   container_name: container_inception_wordpress
#   restart: always

# nginx:    #webserver service
#   profiles: ["default", "server"]
#   build:
#     context: ./requirements/nginx
#     dockerfile: Dockerfile
#   container_name: container_inception_nginx
#   ports:
#     - 443:443
#   restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

networks:
    inception:
        name: inception
        driver: bridge
