# Docker version 25.0.3 (windows)
# Docker version 26.0.2, build 3c863ff (vms)

name: inception

services:
  mariadb:  #database service
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_socket:/run/mysqld
    env_file:
      - .env
    secrets:
      - mariadb_root_password
      - wordpress_user_password
      - wordpress_admin_password
    ports:
      - 3306:3306

  wordpress: #php & wordpress service
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - mariadb_socket:/run/mysqld
    env_file:
      - .env
    secrets:
      - mariadb_root_password
      - wordpress_user_password
      - wordpress_admin_password
    ports:
      - 9000:9000
    depends_on:
      - mariadb

  nginx: #webserver service
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

  mariadb_socket:
    name: mariadb_socket

secrets:
  mariadb_root_password:
    file: ../secrets/.secrets_db_root
  wordpress_user_password:
    file: ../secrets/.secrets_wp_user
  wordpress_admin_password:
    file: ../secrets/.secrets_wp_admin

networks:
    default:
      name: inception
      driver: bridge
