# Docker version 25.0.3 (windows)
# Docker version 26.0.2, build 3c863ff (vms)

#@note add whitespaces to arrange values?
#@note mariadb socket?

name: inception

services:
  mariadb:  #database service
    profiles: ["default", "db"]
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_HOST=%
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_socket:/run/mysqld
    env_file:
      - .env
    ports:
      - 3306:3306

  wordpress: #php & wordpress service
    profiles: ["default", "wp"]
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - mariadb_socket:/run/mysqld
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

  mariadb_socket:
    name: mariadb_socket

networks:
    default:
      name: inception
      driver: bridge

# nginx:    #webserver service
#   profiles: ["default", "server"]
#   build:
#     context: ./requirements/nginx
#     dockerfile: Dockerfile
#   container_name: container_inception_nginx
#   ports:
#     - 443:443
#   restart: always
