# Docker version 24.0.2 (compose v2)

services:
  nginx:    #webserver service
    profiles: ["default", "server"]
    image: inception_nginx
    container_name: inception_nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    restart: always

  mariadb:  #database service
    profiles: ["default", "db"]
    image: inception_mariadb
    container_name: inception_mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data:
    driver: local

