# Docker version 25.0.3 (windows)

# @note add prefix for names

name: inception

services:
  nginx:    #webserver service
    profiles: ["default", "server"]
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: container_inception_nginx
    ports:
      - 443:443
    restart: always

  mariadb:  #database service
    profiles: ["default", "db"]
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: container_inception_mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  wordpress: #php & wordpress service
    profiles: ["default", "wp"]
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: container_inception_wordpress
    restart: always

volumes:
  mariadb_data:
    driver: local

