# docker version 26.0.2 on ubuntu 22.04

# docker-compose != docker compose
# docker-compose migrated to docker compose v2
# version 3. and older are considered compose v1
# version statement is obsolete as of v2

# this file is responsible for:
# - setting up project, image and container names
# - setting up start up order (mariadb -> wordpress -> nginx)
# - setting up docker network and exposing ports
# - setting up volumes (so files are shared)
# - submitting environment variables and secrets (passwords) to container FS

name: inception

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_socket:/run/mysqld
    env_file:
      - .env
    secrets:
      - mariadb_root_password
      - mariadb_user_password
      - wordpress_user_password
      - wordpress_admin_password
    ports:
      - 3306:3306

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - mariadb_socket:/run/mysqld
    env_file:
      - .env
    secrets:
      - mariadb_user_password
      - wordpress_user_password
      - wordpress_admin_password
    ports:
      - 9000:9000
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

  mariadb_socket:
    name: mariadb_socket

secrets:
  mariadb_root_password:
    file: ../secrets/.secrets_db_root
  mariadb_user_password:
    file: ../secrets/.secrets_db_user
  wordpress_user_password:
    file: ../secrets/.secrets_wp_user
  wordpress_admin_password:
    file: ../secrets/.secrets_wp_admin

networks:
    default:
      name: inception
      driver: bridge
