#!/bin/bash

MARIADB_ROOT_PASSWORD=$(cat /run/secrets/mariadb_root_password)
MARIADB_USER_PASSWORD=$(cat /run/secrets/mariadb_user_password)
DEST_FILE=/etc/mysql/init.sql

echo "CREATE DATABASE IF NOT EXISTS $MARIADB_DB_NAME;" > $DEST_FILE
echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MARIADB_ROOT_PASSWORD';" >> $DEST_FILE
echo "CREATE USER IF NOT EXISTS '$MARIADB_USER_NAME'@'%' IDENTIFIED BY '$MARIADB_USER_PASSWORD';" >> $DEST_FILE
echo "GRANT ALL PRIVILEGES ON $MARIADB_DB_NAME.* TO '$MARIADB_USER_NAME'@'%' IDENTIFIED BY '$MARIADB_USER_PASSWORD';" >> $DEST_FILE
echo "FLUSH PRIVILEGES;" >> $DEST_FILE

exec mariadbd --init-file $DEST_FILE
